# ----------------------------------------
# Created on: Tue Nov  8 17:13:52 2022
# Auto generated by Pango
# ----------------------------------------

vsim  -novopt  -L work -L vsim -L adc -L ddrc -L ddrphy -L hsst_e2 -L iolhr_dft -L ipal_e1 -L pciegen2 -sdfmax /top_inst=top_sta.sdf final_sim
add wave *
view wave
view structure
view signals

run 1000ns

# ----------------------------------------
