# ----------------------------------------
# Created on: Tue Nov  8 17:13:52 2022
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  vsim "D:/hdmi_final/pango_sim_libraries/vsim"
vmap  adc "D:/hdmi_final/pango_sim_libraries/adc"
vmap  ddrc "D:/hdmi_final/pango_sim_libraries/ddrc"
vmap  ddrphy "D:/hdmi_final/pango_sim_libraries/ddrphy"
vmap  hsst_e2 "D:/hdmi_final/pango_sim_libraries/hsst_e2"
vmap  iolhr_dft "D:/hdmi_final/pango_sim_libraries/iolhr_dft"
vmap  ipal_e1 "D:/hdmi_final/pango_sim_libraries/ipal_e1"
vmap  pciegen2 "D:/hdmi_final/pango_sim_libraries/pciegen2"
vlog   "top_sim.v" -work work
vlog   "D:/hdmi_final/source/fin_sim.v" -work work

# ----------------------------------------
