# ----------------------------------------
# Created on: Tue Nov  8 19:38:02 2022
# Auto generated by Pango
# ----------------------------------------

vsim  -novopt  -L work -L vsim -L adc -L ddrc -L ddrphy -L hsst_e2 -L iolhr_dft -L ipal_e1 -L pciegen2 final_sim
add wave *
view wave
view structure
view signals

run 1000ns

# ----------------------------------------
