# ----------------------------------------
# Created on: Tue Nov  8 19:26:14 2022
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "D:/hdmi_final/pango_sim_libraries/usim"
vmap  adc "D:/hdmi_final/pango_sim_libraries/adc"
vmap  ddrc "D:/hdmi_final/pango_sim_libraries/ddrc"
vmap  ddrphy "D:/hdmi_final/pango_sim_libraries/ddrphy"
vmap  hsst_e2 "D:/hdmi_final/pango_sim_libraries/hsst_e2"
vmap  iolhr_dft "D:/hdmi_final/pango_sim_libraries/iolhr_dft"
vmap  ipal_e1 "D:/hdmi_final/pango_sim_libraries/ipal_e1"
vmap  pciegen2 "D:/hdmi_final/pango_sim_libraries/pciegen2"
vlog   "D:/hdmi_final/source/source/areaconfig.v" -work work
vlog   "D:/hdmi_final/source/source/data_to_block.sv" -work work
vlog   "D:/hdmi_final/source/source/divider_cell.v" -work work
vlog   "D:/hdmi_final/source/source/led_top.sv" -work work
vlog   "D:/hdmi_final/source/source/cal_block_rest.v" -work work
vlog   "D:/hdmi_final/source/source/divider.v" -work work
vlog   "D:/hdmi_final/source/source/areaconfig3.v" -work work
vlog   "D:/hdmi_final/source/source/cal_block.sv" -work work
vlog   "D:/hdmi_final/source/source/outputdata.v" -work work
vlog   "D:/hdmi_final/source/source/areaconfig4.v" -work work
vlog   "D:/hdmi_final/source/source/block_re.v" -work work
vlog   "D:/hdmi_final/source/source/collect.sv" -work work
vlog   "D:/hdmi_final/source/source/choose.v" -work work
vlog   "D:/hdmi_final/source/source/panduan.v" -work work
vlog   "D:/hdmi_final/source/source/led.v" -work work
vlog   "D:/hdmi_final/source/source/register.v" -work work
vlog   "D:/hdmi_final/source/source/hdmi_input.v" -work work
vlog   "D:/hdmi_final/source/source/top.sv" -work work
vlog   "D:/hdmi_final/source/source/judge_rest.v" -work work
vlog   "D:/hdmi_final/source/source/areaconfi2.v" -work work
vlog   "D:/hdmi_final/ipcore/cl_xiz_0/cl_xiz_0.v" -work work
vlog   "D:/hdmi_final/ipcore/G_re/rtl/ipm_distributed_sdpram_v1_2_G_re.v" -work work
vlog   "D:/hdmi_final/ipcore/G_re/G_re.v" -work work
vlog   "D:/hdmi_final/ipcore/clk_wiz_2/clk_wiz_2.v" -work work
vlog   "D:/hdmi_final/source/fin_sim.v" -work work

# ----------------------------------------
